import type { Metadata } from "next";
import localFont from "next/font/local";
import {Orbitron} from "next/font/google";
import "./globals.css";
import './globalIcons.css';
import GlobalNavBar from "./components/GlobalNavBar";
import { Providers } from "./providers";

// LOCAL FONTS 
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// GOOGLE FONTS
//https://fonts.google.com/specimen/Orbitron
const orbitron = Orbitron({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-orbitron'
})

export const metadata: Metadata = {
  title: "Racing Rumble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased`}>
        <Providers>
          <GlobalNavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
